language: cpp
compiler:
  - gcc

os: linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-7
  env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script:
  - ./pre_build.sh
  - ./build.sh
  - ./test.sh
