language: cpp
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake

install:
- export CXX=g++-7

script:
  - ./pre_build.sh
  - ./build.sh
  - ./test.sh
